import { defineDocs } from "@farming-labs/docs";
import { colorful } from "@farming-labs/theme/colorful";

export default defineDocs({
  entry: "docs",
  theme: colorful(),
  ordering: [
    {
      "slug": "quickstart"
    },
    {
      "slug": "installation"
    },
    {
      "slug": "features",
      "children": [
        {
          "slug": "developer-tools"
        },
        {
          "slug": "documentation-lookup"
        }
      ]
    },
    {
      "slug": "self-hosting",
      "children": [
        {
          "slug": "astro"
        }
      ]
    },
    {
      "slug": "configuration",
      "children": [
        {
          "slug": "deployment"
        }
      ]
    },
    {
      "slug": "guides",
      "children": [
        {
          "slug": "cli-usage"
        }
      ]
    },
    {
      "slug": "api",
      "children": [
        {
          "slug": "cli",
          "children": [
            {
              "slug": "usage"
            }
          ]
        },
        {
          "slug": "config",
          "children": [
            {
              "slug": "runtime"
            }
          ]
        }
      ]
    },
    {
      "slug": "architecture",
      "children": [
        {
          "slug": "overview"
        }
      ]
    },
    {
      "slug": "assets",
      "children": [
        {
          "slug": "endpoint"
        },
        {
          "slug": "services"
        }
      ]
    },
    {
      "slug": "backend",
      "children": [
        {
          "slug": "systems"
        }
      ]
    },
    {
      "slug": "build",
      "children": [
        {
          "slug": "package-structure"
        }
      ]
    },
    {
      "slug": "cli",
      "children": [
        {
          "slug": "tooling"
        }
      ]
    },
    {
      "slug": "content",
      "children": [
        {
          "slug": "runtime-assets"
        },
        {
          "slug": "runtime"
        }
      ]
    },
    {
      "slug": "frontend",
      "children": [
        {
          "slug": "application"
        }
      ]
    }
  ],
  metadata: {
    titleTemplate: "%s – Docs",
    description: "Generated by @farming-labs/docs Cloud",
  },
});
