import { defineDocs } from "@farming-labs/docs";
import { colorful } from "@farming-labs/theme/colorful";

export default defineDocs({
  entry: "docs",
  theme: colorful(),
  ordering: [
    {
      "slug": "quickstart"
    },
    {
      "slug": "installation"
    },
    {
      "slug": "features",
      "children": [
        {
          "slug": "developer-tools"
        }
      ]
    },
    {
      "slug": "self-hosting",
      "children": [
        {
          "slug": "astro"
        }
      ]
    },
    {
      "slug": "configuration",
      "children": [
        {
          "slug": "deployment"
        },
        {
          "slug": "environment"
        }
      ]
    },
    {
      "slug": "guides",
      "children": [
        {
          "slug": "cli-usage"
        }
      ]
    },
    {
      "slug": "api",
      "children": [
        {
          "slug": "cli",
          "children": [
            {
              "slug": "usage"
            }
          ]
        },
        {
          "slug": "config",
          "children": [
            {
              "slug": "runtime"
            }
          ]
        },
        {
          "slug": "exports"
        }
      ]
    },
    {
      "slug": "assets",
      "children": [
        {
          "slug": "endpoint"
        },
        {
          "slug": "services"
        }
      ]
    },
    {
      "slug": "cli",
      "children": [
        {
          "slug": "add"
        },
        {
          "slug": "check"
        },
        {
          "slug": "db"
        },
        {
          "slug": "dev"
        },
        {
          "slug": "docs"
        },
        {
          "slug": "info"
        },
        {
          "slug": "preferences"
        },
        {
          "slug": "preview"
        },
        {
          "slug": "sync"
        },
        {
          "slug": "telemetry"
        }
      ]
    },
    {
      "slug": "content",
      "children": [
        {
          "slug": "runtime-assets"
        },
        {
          "slug": "runtime"
        }
      ]
    },
    {
      "slug": "core",
      "children": [
        {
          "slug": "app"
        },
        {
          "slug": "client-directive"
        },
        {
          "slug": "compile"
        },
        {
          "slug": "config"
        },
        {
          "slug": "cookies"
        },
        {
          "slug": "dev"
        },
        {
          "slug": "errors"
        },
        {
          "slug": "fs"
        },
        {
          "slug": "logger"
        },
        {
          "slug": "middleware"
        },
        {
          "slug": "module-loader"
        },
        {
          "slug": "preview"
        },
        {
          "slug": "redirects"
        },
        {
          "slug": "render"
        },
        {
          "slug": "routing"
        },
        {
          "slug": "sync"
        }
      ]
    },
    {
      "slug": "packages",
      "children": [
        {
          "slug": "astro"
        }
      ]
    },
    {
      "slug": "runtime",
      "children": [
        {
          "slug": "client"
        },
        {
          "slug": "compiler"
        },
        {
          "slug": "server"
        }
      ]
    },
    {
      "slug": "vite-plugin-html",
      "children": [
        {
          "slug": "transform"
        }
      ]
    }
  ],
  metadata: {
    titleTemplate: "%s – Docs",
    description: "Generated by @farming-labs/docs Cloud",
  },
});
