import { defineDocs } from "@farming-labs/docs";
import { colorful } from "@farming-labs/theme/colorful";

export default defineDocs({
  entry: "docs",
  theme: colorful(),
  ordering: [
    {
      "slug": "quickstart"
    },
    {
      "slug": "installation"
    },
    {
      "slug": "configuration",
      "children": [
        {
          "slug": "deployment"
        }
      ]
    },
    {
      "slug": "assets",
      "children": [
        {
          "slug": "services"
        },
        {
          "slug": "endpoint"
        }
      ]
    },
    {
      "slug": "content",
      "children": [
        {
          "slug": "runtime"
        },
        {
          "slug": "runtime-assets"
        }
      ]
    }
  ],
  metadata: {
    titleTemplate: "%s – Docs",
    description: "Generated by @farming-labs/docs Cloud",
  },
});
